<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
// connect to database
$link = mysqli_connect("localhost", "--------", "---------------------", "--------")
or die('Could not connect ');

mysqli_query($link, "DELETE FROM MUSICIAN_RATING");
mysqli_query($link, "DELETE FROM M_GENRES");
mysqli_query($link, "DELETE FROM M_INSTRUMENTS");
mysqli_query($link, "DELETE FROM MUSICIAN");
mysqli_query($link, "DELETE FROM BAND_SOC_MEDIA");  
mysqli_query($link, "DELETE FROM PATRON_STREAMING_PLATFORMS");
mysqli_query($link, "DELETE FROM PATRON_GENRES");
mysqli_query($link, "DELETE FROM BAND_GENRES");
mysqli_query($link, "DELETE FROM BAND");
mysqli_query($link, "DELETE FROM MANAGER");
mysqli_query($link, "DELETE FROM VENUE");
mysqli_query($link, "DELETE FROM PATRON");

mysqli_query($link, "INSERT INTO PATRON (p_email, p_name, p_birthdate, profile_picture) VALUES 
  ('AAAAA@AAAA.AAAAA', 'DELETE ME PLEASE OMG PLEASE', '2023-01-01', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679086737/CS340/34667_main_mr1k_cvavsd.png'), 
  ('bigdan@aol.com', 'Bigdan', '1991-05-28', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679082899/CS340/IMG_20210811_151743_sinjo8.png'), 
  ('blobdan@gmail.com', 'Blobdan', '1996-10-04', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679082740/CS340/IMG_20200603_185047_axg2g2.png'),
  ('blogdan@gmail.com', 'Blogdan', '1997-11-09', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679082821/CS340/IMG_20210305_134759_ttudnf.png'), 
  ('bogdan@mails.gg', 'Bigz', '1985-02-19', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679083446/CS340/IMG_20200928_163257_hf5ia8.png'),
  ('bogdan@yahoo.co.in', 'Barfdan', '1990-05-19', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679083196/CS340/IMG_20200924_165245_iajtjm.png'),
  ('bogz@tuta.io', 'Bogz', '2003-08-26', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679083081/CS340/IMG_20200506_040319_bs5czw.png'),
  ('dog@dog.dog', 'Dog', '2021-05-01', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679084253/CS340/IMG_20230105_184027_ffwfha.png'),
  ('dog@dog.fart', 'Also Dog', '2021-05-01', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679084418/CS340/VID_20220214_212516_LS_m94cfk.png'),
  ('dog@dog.woof', 'More Dog', '2021-05-01', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679084340/CS340/IMG_20220205_105721_zkfo61.png'),
  ('dog@dog.sniff', 'Dog Dog', '2021-05-01', 'https://res.cloudinary.com/damsyjmve/image/upload/v1679084094/CS340/IMG_20220204_161053_slhfc7.png')");

mysqli_query($link, "INSERT INTO VENUE (v_email, v_name, v_type, capacity, price_range, v_address, v_number, dancefloor, hours) VALUES
  ('thebluenote@gmail.com', 'The Blue Note', 'Music Club', 200, '***', '123 Main St', '555-1234', TRUE, '7pm-2am'),
  ('boogiewoogies@gmail.com', 'Boogie Woogie Hall', 'Dance Hall', 300, '***', '456 Park Ave', '555-5678', TRUE, '6pm-12am'),
  ('crazyhorsetavern@gmail.com', 'Crazy Horse Tavern', 'Bar', 100, '***', '789 Elm St', '555-9012', FALSE, '4pm-2am'),
  ('coolbeachclub@gmail.com', 'Cool Beach Club', 'Beach Club', 500, '**', '100 Beach Blvd', '555-3456', TRUE, '10am-6pm'),
  ('oldtownhall@gmail.com', 'Old Town Hall', 'Community Center', 150, '*****', '1 First St', '555-7890', FALSE, '9am-9pm'),
  ('skylinehotel@gmail.com', 'Skyline Hotel', 'Hotel', 400, '****', '333 Main St', '555-2345', FALSE, '24 hours'),
  ('redcarpetclub@gmail.com', 'Red Carpet Club', 'Nightclub', 250, '*', '246 Elm St', '555-6789', TRUE, '10pm-3am'),
  ('uptownhall@gmail.com', 'Uptown Hall', 'Community Center', 200, '***', '777 Fifth Ave', '555-0123', TRUE, '10am-10pm'),
  ('jazzlounge@gmail.com', 'Jazz Lounge', 'Lounge', 75, '**', '888 Jazz St', '555-4567', TRUE, '8pm-1am'),
  ('thepaddock@gmail.com', 'The Paddock', 'Racetrack', 1000, '**', '777 Raceway', '555-7890', FALSE, '1pm-9pm'),
  ('downtowndeli@gmail.com', 'Downtown Deli', 'Restaurant', 50, '****', '444 Main St', '555-2345', FALSE, '11am-9pm'),
  ('uptowncafe@gmail.com', 'Uptown Cafe', 'Cafe', 30, '*', '222 First Ave', '555-6789', FALSE, '8am-7pm'),
  ('sunsetgrill@gmail.com', 'Sunset Grill', 'Restaurant', 100, '****', '345 Beach Blvd', '555-0123', FALSE, '11am-11pm'),
  ('redrockcasino@gmail.com', 'Red Rock Casino', 'Casino', 1000, '**', '555 Casino Blvd', '555-4567', FALSE, '24 hours'),
  ('oceanfrontresort@gmail.com', 'Oceanfront Resort', 'Resort', 800, '****', '777 Ocean Blvd', '555-7890', FALSE, '24 hours')");

mysqli_query($link, "INSERT INTO MANAGER (mgr_email, mgr_name, mgr_address, mgr_number, website)
VALUES 
  ('johndoe@gmail.com', 'John Doe', '123 Main St, Anytown, USA', '555-1234', 'www.johndoemanagement.com'),
  ('janesmith@yahoo.com', 'Jane Smith', '456 Oak St, Anycity, USA', '555-5678', 'www.janesmithmanagement.com'),
  ('miketurner@gmail.com', 'Mike Turner', '789 Elm St, Anystate, USA', '555-9012', 'www.miketurnermanagement.com'),
  ('sarahjones@yahoo.com', 'Sarah Jones', '111 Maple St, Anyville, USA', '555-3456', 'www.sarahjonesmanagement.com'),
  ('bobwhite@gmail.com', 'Bob White', '222 Cedar St, Anymetropolis, USA', '555-7890', 'www.bobwhitemanagement.com'),
  ('amycarter@yahoo.com', 'Amy Carter', '333 Pine St, Anyhamlet, USA', '555-2345', 'www.amycartermanagement.com'),
  ('mattbrown@gmail.com', 'Matt Brown', '444 Oak St, Anyborough, USA', '555-6789', 'www.mattbrownmanagement.com'),
  ('jenniferadams@yahoo.com', 'Jennifer Adams', '555 Elm St, Anyvillage, USA', '555-0123', 'www.jenniferadamsmanagement.com'),
  ('andrewcohen@gmail.com', 'Andrew Cohen', '666 Maple St, Anytown, USA', '555-4567', 'www.andrewcohenmanagement.com'),
  ('lisawilson@yahoo.com', 'Lisa Wilson', '777 Cedar St, Anycity, USA', '555-8901', 'www.lisawilsonmanagement.com'),
  ('johnbrown@gmail.com', 'John Brown', '888 Pine St, Anystate, USA', '555-2345', 'www.johnbrownmanagement.com'),
  ('marylee@yahoo.com', 'Mary Lee', '999 Oak St, Anyville, USA', '555-6789', 'www.maryleemanagement.com'),
  ('chrisgarcia@gmail.com', 'Chris Garcia', '123 Cherry St, Anymetropolis, USA', '555-0123', 'www.chrisgarciamanagement.com'),
  ('jessicasimpson@yahoo.com', 'Jessica Simpson', '456 Peach St, Anyhamlet, USA', '555-4567', 'www.jessicasimpsonmanagement.com'),
  ('peterwang@gmail.com', 'Peter Wang', '789 Plum St, Anytown, USA', '555-8901', 'www.peterwangmanagement.com')");

mysqli_query($link, "INSERT INTO BAND (b_email, b_name, b_location, forming_year, b_desc, mgr_email) VALUES
  ('acousticjams@gmail.com', 'Acoustic Jams', 'New York', 2010, 'A band that plays acoustic versions of popular hits', 'johndoe@gmail.com'),
  ('bluesnation@hotmail.com', 'Blues Nation', 'Chicago', 2005, 'A blues band with a soulful sound', 'janesmith@yahoo.com'),
  ('thefunksters@gmail.com', 'The Funksters', 'Los Angeles', 2012, 'A funky band that will get you dancing', 'marylee@yahoo.com'),
  ('thejazzcats@yahoo.com', 'The Jazz Cats', 'New Orleans', 2008, 'A jazz band that plays classic standards', 'johndoe@gmail.com'),
  ('rocknation@gmail.com', 'Rock Nation', 'Seattle', 2015, 'A rock band with a hard-driving sound', 'peterwang@gmail.com'),
  ('hiphopheads@gmail.com', 'Hip Hop Heads', 'Atlanta', 2010, 'A hip hop collective that blends old-school and new-school sounds', 'johndoe@gmail.com'),
  ('guitarheroes@hotmail.com', 'Guitar Heroes', 'Nashville', 2005, 'A band that pays tribute to the greatest guitarists of all time', 'lisawilson@yahoo.com'),
  ('soulvibes@yahoo.com', 'Soul Vibes', 'Detroit', 2012, 'A soul band that will make you feel good', 'miketurner@gmail.com'),
  ('metalheads@gmail.com', 'Metal Heads', 'Los Angeles', 2008, 'A heavy metal band with a powerful sound', 'johndoe@gmail.com'),
  ('countryroads@hotmail.com', 'Country Roads', 'Nashville', 2015, 'A country band that plays all the hits', 'miketurner@gmail.com'),
  ('thebluesbrothers@gmail.com', 'The Blues Brothers', 'Chicago', 2010, 'A blues band that pays tribute to the greats', 'johndoe@gmail.com'),
  ('jazzfunkmasters@hotmail.com', 'Jazz Funk Masters', 'New York', 2005, 'A jazz-funk band with a groovy sound', 'marylee@yahoo.com'),
  ('popprincesses@yahoo.com', 'Pop Princesses', 'Los Angeles', 2012, 'A pop band with catchy tunes and danceable beats', 'marylee@yahoo.com'),
  ('progrockers@gmail.com', 'Prog Rockers', 'Seattle', 2008, 'A progressive rock band that takes you on a journey', 'johndoe@gmail.com'),
  ('reggaevibes@hotmail.com', 'Reggae Vibes', 'Jamaica', 2015, 'A reggae band that spreads good vibes', 'johnbrown@gmail.com'),
  ('thebeatchildren@gmail.com', 'The Beat Children', 'New York', 2010, 'A band that mixes old-school and new-school sounds to create a unique sound', 'johndoe@gmail.com'),
  ('funkytown@hotmail.com', 'Funky Town', 'Los Angeles', 2005, 'A funk band that will get you grooving', 'johnbrown@gmail.com'),
  ('rockrebels@yahoo.com', 'Rock Rebels', 'Seattle', 2012, 'A band that plays hard rock with a rebellious attitude', 'amycarter@yahoo.com')");

mysqli_query($link, "INSERT INTO BAND_GENRES (b_email, b_genre) VALUES
  ('acousticjams@gmail.com', 'pop'),
  ('acousticjams@gmail.com', 'rock'),
  ('bluesnation@hotmail.com', 'blues'),
  ('thefunksters@gmail.com', 'funk'),
  ('thefunksters@gmail.com', 'soul'),
  ('thejazzcats@yahoo.com', 'jazz'),
  ('rocknation@gmail.com', 'rock'),
  ('hiphopheads@gmail.com', 'hip hop'),
  ('guitarheroes@hotmail.com', 'rock'),
  ('guitarheroes@hotmail.com', 'blues'),
  ('soulvibes@yahoo.com', 'soul'),
  ('metalheads@gmail.com', 'metal'),
  ('countryroads@hotmail.com', 'country'),
  ('thebluesbrothers@gmail.com', 'blues'),
  ('jazzfunkmasters@hotmail.com', 'jazz'),
  ('jazzfunkmasters@hotmail.com', 'funk'),
  ('popprincesses@yahoo.com', 'pop'),
  ('progrockers@gmail.com', 'rock'),
  ('progrockers@gmail.com', 'progressive'),
  ('reggaevibes@hotmail.com', 'reggae'),
  ('thebeatchildren@gmail.com', 'pop'),
  ('thebeatchildren@gmail.com', 'hip hop'),
  ('funkytown@hotmail.com', 'funk'),
  ('rockrebels@yahoo.com', 'rock')");

mysqli_query($link, "INSERT INTO PATRON_GENRES (p_email, p_genre) VALUES
  ('bigdan@aol.com', 'hip-hop'),
  ('bigdan@aol.com', 'r&b'),
  ('blobdan@gmail.com', 'pop'),
  ('blobdan@gmail.com', 'rock'),
  ('blogdan@gmail.com', 'country'),
  ('blogdan@gmail.com', 'folk'),
  ('bogdan@mails.gg', 'electronic'),
  ('bogdan@mails.gg', 'dance'),
  ('bogdan@yahoo.co.in', 'jazz'),
  ('bogz@tuta.io', 'classical'),
  ('bogz@tuta.io', 'opera'),
  ('dog@dog.dog', 'reggae'),
  ('dog@dog.fart', 'heavy metal'),
  ('dog@dog.woof', 'indie'),
  ('dog@dog.sniff', 'alternative')");

mysqli_query($link, "INSERT INTO PATRON_STREAMING_PLATFORMS (p_email, p_platform) VALUES
  ('bigdan@aol.com', 'Spotify'),
  ('bigdan@aol.com', 'Apple Music'),
  ('bigdan@aol.com', 'YouTube Music'),
  ('blobdan@gmail.com', 'Spotify'),
  ('blobdan@gmail.com', 'Amazon Music'),
  ('blogdan@gmail.com', 'Spotify'),
  ('blogdan@gmail.com', 'Pandora'),
  ('blogdan@gmail.com', 'iHeartRadio'),
  ('bogdan@mails.gg', 'Spotify'),
  ('bogdan@mails.gg', 'Tidal'),
  ('bogdan@mails.gg', 'SoundCloud'),
  ('bogdan@yahoo.co.in', 'Apple Music'),
  ('bogdan@yahoo.co.in', 'Deezer'),
  ('bogz@tuta.io', 'Spotify'),
  ('dog@dog.dog', 'Spotify'),
  ('dog@dog.dog', 'YouTube Music'),
  ('dog@dog.fart', 'Spotify'),
  ('dog@dog.fart', 'Apple Music'),
  ('dog@dog.woof', 'Spotify'),
  ('dog@dog.woof', 'Tidal'),
  ('dog@dog.sniff', 'Spotify'),
  ('dog@dog.sniff', 'Pandora')");

mysqli_query($link, "INSERT INTO BAND_SOC_MEDIA (b_email, soc_media) VALUES
  ('acousticjams@gmail.com', 'https://www.facebook.com/acousticjams'),
  ('acousticjams@gmail.com', 'https://twitter.com/acousticjams'),
  ('bluesnation@hotmail.com', 'https://www.facebook.com/bluesnation'),
  ('bluesnation@hotmail.com', 'https://www.instagram.com/bluesnation'),
  ('thefunksters@gmail.com', 'https://twitter.com/thefunksters'),
  ('thefunksters@gmail.com', 'https://www.instagram.com/thefunksters'),
  ('thejazzcats@yahoo.com', 'https://www.facebook.com/thejazzcats'),
  ('thejazzcats@yahoo.com', 'https://www.twitter.com/thejazzcats'),
  ('rocknation@gmail.com', 'https://www.facebook.com/rocknation'),
  ('rocknation@gmail.com', 'https://www.instagram.com/rocknation'),
  ('hiphopheads@gmail.com', 'https://www.facebook.com/hiphopheads'),
  ('hiphopheads@gmail.com', 'https://www.twitter.com/hiphopheads'),
  ('guitarheroes@hotmail.com', 'https://www.facebook.com/guitarheroes'),
  ('guitarheroes@hotmail.com', 'https://www.instagram.com/guitarheroes'),
  ('soulvibes@yahoo.com', 'https://www.twitter.com/soulvibes'),
  ('soulvibes@yahoo.com', 'https://www.instagram.com/soulvibes'),
  ('metalheads@gmail.com', 'https://www.facebook.com/metalheads'),
  ('metalheads@gmail.com', 'https://www.twitter.com/metalheads'),
  ('countryroads@hotmail.com', 'https://www.facebook.com/countryroads'),
  ('countryroads@hotmail.com', 'https://www.instagram.com/countryroads'),
  ('thebluesbrothers@gmail.com', 'https://www.facebook.com/thebluesbrothers'),
  ('thebluesbrothers@gmail.com', 'https://www.twitter.com/thebluesbrothers'),
  ('jazzfunkmasters@hotmail.com', 'https://www.facebook.com/jazzfunkmasters'),
  ('jazzfunkmasters@hotmail.com', 'https://www.instagram.com/jazzfunkmasters'),
  ('popprincesses@yahoo.com', 'https://www.twitter.com/popprincesses'),
  ('popprincesses@yahoo.com', 'https://www.instagram.com/popprincesses'),
  ('progrockers@gmail.com', 'https://www.facebook.com/progrockers'),
  ('progrockers@gmail.com', 'https://www.twitter.com/progrockers'),
  ('reggaevibes@hotmail.com', 'https://www.facebook.com/reggaevibes'),
  ('reggaevibes@hotmail.com', 'https://www.instagram.com/reggaevibes'),
  ('thebeatchildren@gmail.com', 'https://www.facebook.com/thebeatchildren'),
  ('thebeatchildren@gmail.com', 'https://www.twitter.com/thebeatchildren'),
  ('funkytown@hotmail.com', 'https://www.facebook.com/funkytown'),
  ('funkytown@hotmail.com', 'https://www.instagram.com/funkytown'),
  ('rockrebels@yahoo.com', 'https://www.twitter.com/rockrebels'),
  ('rockrebels@yahoo.com', 'https://www.instagram.com/rockrebels')");

mysqli_query($link, "INSERT INTO MUSICIAN (m_email, m_name, m_birthdate, vocals, fulltime, m_desc) VALUES
  ('johnsmith@gmail.com', 'John Smith', '1985-03-15', FALSE, TRUE, 'Experienced drummer available for gigs and recording projects.'),
  ('janedoe@yahoo.com', 'Jane Doe', '1990-06-23', TRUE, TRUE, 'Professional singer with a versatile voice.'),
  ('bobross@hotmail.com', 'Bob Ross', '1979-11-02', FALSE, TRUE, 'Bass player with a solid groove.'),
  ('davidsmith@gmail.com', 'David Smith', '1987-01-30', TRUE, TRUE, 'Talented guitarist with experience in a variety of styles.'),
  ('emilynguyen@yahoo.com', 'Emily Nguyen', '1993-08-12', TRUE, FALSE, 'Keyboardist and composer looking to collaborate on new projects.'),
  ('robertjohnson@hotmail.com', 'Robert Johnson', '1995-05-01', TRUE, FALSE, 'Up-and-coming singer-songwriter with a unique sound.'),
  ('briantaylor@gmail.com', 'Brian Taylor', '1984-09-17', FALSE, TRUE, 'Experienced bassist with a background in jazz and funk.'),
  ('lisawilliams@yahoo.com', 'Lisa Williams', '1991-02-25', TRUE, FALSE, 'Pianist and composer with a passion for classical music.'),
  ('kevinbrown@hotmail.com', 'Kevin Brown', '1988-07-08', TRUE, TRUE, 'Guitarist and singer with a soulful sound.'),
  ('danieljohnson@gmail.com', 'Daniel Johnson', '1982-04-11', FALSE, TRUE, 'Drummer with experience in a variety of genres.'),
  ('sarahlee@yahoo.com', 'Sarah Lee', '1994-11-27', TRUE, FALSE, 'Singer-songwriter with a love for acoustic music.'),
  ('jasonmiller@hotmail.com', 'Jason Miller', '1986-12-19', FALSE, TRUE, 'Bass player with experience in rock and metal.'),
  ('katiejones@gmail.com', 'Katie Jones', '1992-03-07', TRUE, FALSE, 'Pianist and singer with a background in pop and rock music.'),
  ('matthewsmith@yahoo.com', 'Matthew Smith', '1983-08-29', TRUE, TRUE, 'Guitarist and songwriter with a passion for indie and alternative music.'),
  ('johndoe@gmail.com', 'John Doe', '1990-01-14', TRUE, FALSE, 'Singer and guitarist with a love for blues and folk music.')");

mysqli_query($link, "INSERT INTO M_INSTRUMENTS (m_email, m_instrument) VALUES
  ('johnsmith@gmail.com', 'drums'),
  ('janedoe@yahoo.com', 'vocals'),
  ('janedoe@yahoo.com', 'guitar'),
  ('bobross@hotmail.com', 'bass'),
  ('davidsmith@gmail.com', 'guitar'),
  ('emilynguyen@yahoo.com', 'keyboard'),
  ('robertjohnson@hotmail.com', 'vocals'),
  ('briantaylor@gmail.com', 'bass'),
  ('lisawilliams@yahoo.com', 'piano'),
  ('kevinbrown@hotmail.com', 'guitar'),
  ('danieljohnson@gmail.com', 'drums'),
  ('sarahlee@yahoo.com', 'vocals'),
  ('sarahlee@yahoo.com', 'guitar'),
  ('jasonmiller@hotmail.com', 'bass'),
  ('katiejones@gmail.com', 'piano'),
  ('katiejones@gmail.com', 'vocals'),
  ('matthewsmith@yahoo.com', 'guitar'),
  ('johndoe@gmail.com', 'vocals'),
  ('johndoe@gmail.com', 'guitar')");

mysqli_query($link, "INSERT INTO M_GENRES (m_email, m_genre) VALUES
  ('johnsmith@gmail.com', 'rock'),
  ('johnsmith@gmail.com', 'pop'),
  ('johnsmith@gmail.com', 'alternative'),
  ('janedoe@yahoo.com', 'jazz'),
  ('janedoe@yahoo.com', 'blues'),
  ('janedoe@yahoo.com', 'pop'),
  ('bobross@hotmail.com', 'rock'),
  ('bobross@hotmail.com', 'metal'),
  ('davidsmith@gmail.com', 'pop'),
  ('davidsmith@gmail.com', 'rock'),
  ('davidsmith@gmail.com', 'indie'),
  ('emilynguyen@yahoo.com', 'pop'),
  ('emilynguyen@yahoo.com', 'classical'),
  ('robertjohnson@hotmail.com', 'acoustic'),
  ('robertjohnson@hotmail.com', 'singer-songwriter'),
  ('briantaylor@gmail.com', 'jazz'),
  ('briantaylor@gmail.com', 'funk'),
  ('lisawilliams@yahoo.com', 'classical'),
  ('kevinbrown@hotmail.com', 'soul'),
  ('kevinbrown@hotmail.com', 'blues'),
  ('danieljohnson@gmail.com', 'rock'),
  ('danieljohnson@gmail.com', 'jazz'),
  ('danieljohnson@gmail.com', 'pop'),
  ('sarahlee@yahoo.com', 'acoustic'),
  ('sarahlee@yahoo.com', 'singer-songwriter'),
  ('jasonmiller@hotmail.com', 'rock'),
  ('jasonmiller@hotmail.com', 'metal'),
  ('katiejones@gmail.com', 'pop'),
  ('katiejones@gmail.com', 'rock'),
  ('matthewsmith@yahoo.com', 'indie'),
  ('matthewsmith@yahoo.com', 'alternative'),
  ('johndoe@gmail.com', 'blues'),
  ('johndoe@gmail.com', 'folk')");

mysqli_query($link, "INSERT INTO MUSICIAN_RATING (m_email, b_email, b_recommends, musician_rating_text) VALUES
  ('bobross@hotmail.com', 'rockrebels@yahoo.com', TRUE, 'Bob is an amazing guitarist and a pleasure to work with.'),
  ('bobross@hotmail.com', 'bluesnation@hotmail.com', TRUE, 'Bob\'s bluesy solos really brought our music to life.'),
  ('briantaylor@gmail.com', 'funkytown@hotmail.com', TRUE, 'Brian\'s funky bass lines kept the groove going all night.'),
  ('danieljohnson@gmail.com', 'reggaevibes@hotmail.com', TRUE, 'Daniel\'s reggae beats were exactly what we needed.'),
  ('davidsmith@gmail.com', 'acousticjams@gmail.com', TRUE, 'David\'s acoustic guitar added a beautiful texture to our songs.'),
  ('emilynguyen@yahoo.com', 'hiphopheads@gmail.com', TRUE, 'Emily\'s rhymes were fire and her flow was impeccable.'),
  ('janedoe@yahoo.com', 'metalheads@gmail.com', TRUE, 'Jane\'s metal screams were out of this world.'),
  ('jasonmiller@hotmail.com', 'progrockers@gmail.com', TRUE, 'Jason\'s keyboard playing really brought out the progressive elements in our music.'),
  ('johndoe@gmail.com', 'thebeatchildren@gmail.com', TRUE, 'John\'s beats were so infectious and got the crowd moving.'),
  ('johnsmith@gmail.com', 'thebluesbrothers@gmail.com', TRUE, 'John\'s bluesy voice is a perfect fit for our band.'),
  ('katiejones@gmail.com', 'thejazzcats@yahoo.com', TRUE, 'Katie\'s jazz vocals were smooth as butter.'),
  ('kevinbrown@hotmail.com', 'guitarheroes@hotmail.com', TRUE, 'Kevin\'s shredding skills are truly legendary.'),
  ('lisawilliams@yahoo.com', 'jazzfunkmasters@hotmail.com', TRUE, 'Lisa\'s saxophone playing added a funky twist to our jazz tunes.'),
  ('matthewsmith@yahoo.com', 'popprincesses@yahoo.com', TRUE, 'Matthew\'s pop beats were exactly what we were looking for.'),
  ('robertjohnson@hotmail.com', 'thefunksters@gmail.com', TRUE, 'Robert\'s funky guitar riffs are the backbone of our sound.'),
  ('sarahlee@yahoo.com', 'countryroads@hotmail.com', TRUE, 'Sarah\'s country fiddle playing is the perfect addition to our band.'),
  ('danieljohnson@gmail.com', 'rocknation@gmail.com', FALSE, 'Unfortunately, Daniel was not a good fit for our band.')");

mysqli_query($link, "INSERT INTO GIG (gig_date, gig_time, price, overage, v_email, b_email) VALUES
  ('2023-05-01', '20:00:00', 50, true, 'boogiewoogies@gmail.com', 'rockrebels@yahoo.com'),
  ('2023-05-02', '21:00:00', 75, false, 'oceanfrontresort@gmail.com', 'bluesnation@hotmail.com'),
  ('2023-05-03', '18:30:00', 100, true, 'downtowndeli@gmail.com', 'funkytown@hotmail.com'),
  ('2023-05-04', '19:00:00', 60, true, 'jazzlounge@gmail.com', 'reggaevibes@hotmail.com'),
  ('2023-05-05', '20:30:00', 80, false, 'uptowncafe@gmail.com', 'acousticjams@gmail.com'),
  ('2023-05-06', '22:00:00', 120, true, 'redrockcasino@gmail.com', 'hiphopheads@gmail.com'),
  ('2023-05-07', '19:30:00', 90, true, 'skylinehotel@gmail.com', 'metalheads@gmail.com'),
  ('2023-05-08', '21:00:00', 70, false, 'sunsetgrill@gmail.com', 'progrockers@gmail.com'),
  ('2023-05-09', '20:00:00', 110, true, 'thebluenote@gmail.com', 'thebeatchildren@gmail.com'),
  ('2023-05-10', '19:00:00', 95, false, 'redcarpetclub@gmail.com', 'thebluesbrothers@gmail.com'),
  ('2023-05-11', '22:00:00', 65, true, 'uptownhall@gmail.com', 'thejazzcats@yahoo.com'),
  ('2023-05-12', '20:30:00', 85, false, 'oceanfrontresort@gmail.com', 'guitarheroes@hotmail.com'),
  ('2023-05-13', '18:00:00', 125, true, 'crazyhorsetavern@gmail.com', 'jazzfunkmasters@hotmail.com'),
  ('2023-05-14', '21:00:00', 75, true, 'uptowncafe@gmail.com', 'popprincesses@yahoo.com'),
  ('2023-05-15', '20:30:00', 95, false, 'oceanfrontresort@gmail.com', 'thefunksters@gmail.com'),
  ('2023-05-16', '19:00:00', 110, true, 'thebluenote@gmail.com', 'countryroads@hotmail.com'),
  ('2023-05-17', '20:00:00', 80, false, 'redcarpetclub@gmail.com', 'soulvibes@yahoo.com'),
  ('2023-05-18', '22:00:00', 60, true, 'skylinehotel@gmail.com', 'rocknation@gmail.com'),
  ('2023-05-19', '19:30:00', 90, true, 'sunsetgrill@gmail.com', 'thebeatchildren@gmail.com'),
  ('2023-05-20', '20:00:00', 70, false, 'uptowncafe@gmail.com', 'metalheads@gmail.com'),
  ('2023-05-04', '20:00:00', 25, false, 'boogiewoogies@gmail.com', 'rockrebels@yahoo.com'),
  ('2023-05-02', '18:30:00', 20, TRUE, 'jazzlounge@gmail.com', 'thejazzcats@yahoo.com'),
  ('2023-05-03', '19:00:00', 30, FALSE, 'uptowncafe@gmail.com', 'popprincesses@yahoo.com'),
  ('2023-05-04', '21:00:00', 15, TRUE, 'downtowndeli@gmail.com', 'acousticjams@gmail.com'),
  ('2023-05-05', '22:00:00', 40, FALSE, 'redrockcasino@gmail.com', 'rocknation@gmail.com'),
  ('2023-05-06', '19:30:00', 50, TRUE, 'skylinehotel@gmail.com', 'metalheads@gmail.com'),
  ('2023-05-07', '20:00:00', 35, FALSE, 'thebluenote@gmail.com', 'jazzfunkmasters@hotmail.com'),
  ('2023-05-08', '18:00:00', 10, TRUE, 'crazyhorsetavern@gmail.com', 'thefunksters@gmail.com'),
  ('2023-05-09', '21:00:00', 20, FALSE, 'oceanfrontresort@gmail.com', 'bluesnation@hotmail.com'),
  ('2023-05-11', '19:00:00', 25, FALSE, 'redcarpetclub@gmail.com', 'funkytown@hotmail.com'),
  ('2023-05-12', '22:00:00', 15, TRUE, 'coolbeachclub@gmail.com', 'reggaevibes@hotmail.com')");

mysqli_close($link); ?>
